name: Create Structured Package Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-structured-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create package structure
      run: |
        mkdir -p package/ProjectData~
        mkdir -p package/Documentation~
        
        cp -r Assets package/ProjectData~/Assets
        cp -r Packages package/ProjectData~/Packages
        cp -r ProjectSettings package/ProjectData~/ProjectSettings
        rm -f package/ProjectData~/ProjectSettings/ProjectVersion.txt
        
        cp Documentation/VSMT.md package/Documentation~/VSMT.md
        cp README.md package/
        cp LICENSE package/
        cp package.json package/

    - name: Create TGZ archive with versioned name
      run: |
        # Remove 'v' prefix if present (v0.1.0 → 0.1.0)
        VERSION=${GITHUB_REF_NAME#v}
        # Create archive with dynamic name
        tar -czf "com.unity.template.vsmt-$VERSION.tgz" package/

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          com.unity.template.vsmt-*.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: rm -rf package/ com.unity.template.vsmt-*.tgz
